### PR TITLE
docker::run - add Restart support to systemd unit file

### PR DESCRIPTION
**Pull request by bwalex**
I've also updated the upstart file, but as far as I can see, that one isn't actually used anymore.

### CODE REVIEW

**Comment by garethr** [comment]
@bwalex is there a reason for this to not be the default? I'm thinking that we wouldn't need the logic and the new flag and we could just add the lines into the systemd config file. This feels like it would be useful in all cases?

**Comment by bwalex** [comment]
It's certainly useful to me, and I can't think of a particularly good reason for it not to be default, other than the usual "someone might not want it". If you think it should be default, and there shouldn't even be a flag to disable it, I can rework the PR to do just that.

**Comment by garethr** [comment]
@bwalex I think that's the right way to go to start with. We can always make it configurable later depending on usage, but it feels like a good sane starting point in any case. Thanks

**Comment by bwalex** [comment]
That's that then, I think.

**Comment by garethr** [comment]
@bwalex thanks, this will go out in next release which should be shortly

**Pull request merged**
