### PR TITLE
adding support for log_level (-l) in docker config files

### PR DESCRIPTION
**Pull request by n0coast**
The default log level for docker is 'info' which can generate a lot of noise, just adding support for the -l|--log-level switch in the docker configs: /etc/conf.d/docker, /etc/default/docker, /etc/sysconfig/docker

From the manpage the usage is:

   -l, --log-level="debug|info|error|fatal""
     Set the logging level. Default is info.

This patch allows the optional docker::params::log_level to be set.

### CODE REVIEW

**Comment by n0coast** [comment]
Sorry for the open/close... somehow the Gemfile.lock got updated, and I didn't want that bit committed.

**Comment by garethr** [comment]
Given we know the valid values for this param it would be nice to put that into the code. Something in init.pp like:

```puppet
validate_re($log_level, '^(debug|info|error|fatal)$', 'log_level must be one of debug, info, error of fatal')
```

A quick unit test for this showing it fail for an invalid value would also be great.

Thanks for this change too, much appreciated.

**Comment by n0coast** [comment]
Good ideas, implemented and build is passing.

**Comment by garethr** [comment]
@n0coast Thanks for this addition, and for adding the additional tests.

**Pull request merged**
