### PR TITLE
Debian jessie

### PR DESCRIPTION
**Pull request by cwerner1**
First steps for Debian Jessie with Systemd

### CODE REVIEW

**Comment by garethr** [comment]
@cwerner1 thanks for adding, much appreciated. Would you be able to update the rspec-puppet tests as well? I see them failing at the moment but I'd probably expect that given the new OS support. The unit tests really help keep things working given the number of contributions. Happy to help if you;re not too familiar with rspec-puppet. I'm also happy to add support to the acceptance tests once this is merged in. Thanks again.

**Comment by Debilski** [comment]
Shouldn’t this rather use the package from jessie-backports instead of `wget -qO- https://get.docker.com/`?

**Comment by fgeek** [comment]
Yes it should use jessie-backports instead.

**Comment by fgeek** [comment]
I tested these changes in my environment and everything looks good.

**Comment by fgeek** [comment]
@cwerner1 Any plans regarding this pull request?

**Comment by garethr** [comment]
I'm currently working on adding support for the new docker repos in https://github.com/garethr/garethr-docker/pull/311 which will include support for Jessie based partly on this PR. I should have that finished shortly all being well.

**Comment by garethr** [comment]
Just tidying up. I'm closing this as mentioned in favour of #311. That should now be working on Debian 7.8 and 8.0 if you'd like to test it out.

**Pull request closed without merging**
