### PR TITLE
simple compose v3, v3.1, v3.2 support

### PR DESCRIPTION
**Pull request by joaquin386**
Simple solution to make docker compose v3 yaml file work with garethr-docker
More things are needed like modifying the dokcer run with the new v3 attributes, next job.

### CODE REVIEW

**Comment by scotty-c** [comment]
Hey @joaquin386 
Thanks for this PR, would you be able to make a small change so it also supports docker compose version `3.1` as listed here https://docs.docker.com/compose/compose-file/compose-versioning/
Once the PR has that functionality it should be good to merge

**Comment by joaquin386** [comment]
When /^3(\.[0-1])*$/
Just putting down the change needed and for future change in case a 3.X is out.
This also goes with the version of docker-compose. By default on this module it is 1.7 and 3.1 should go with 1.12 (but this should be done more carefull since certain tags got deprecated from 2 to 3)

**Comment by dbason** [comment]
:+1

**Comment by joaquin386** [comment]
Added the new Line for support for docker-compose 3 and 3.1

when /^2(\.0)?$/, /^3(\.[0-2])*$/

**Comment by scotty-c** [comment]
Thanks for the PR !!!

**Pull request merged**
