### PR TITLE
fix #466: add param for choosing install_path of docker-compose

### LINKED ISSUE #466: Could not find a suitable provider for docker_compose (when run from cron)
Hi,

Ubuntu 14.04, puppet 3.8.6, docker 1.9.1, docker-compose 1.5.2

My manifest:
```
    docker_compose { "$compose_dest_dir/$compose_file":
      ensure => present,
    }
```

I run puppet agent -t from cron and the result is:
```
puppet-agent[28092]: Could not find a suitable provider for docker_compose
```
When I run with debug:
```
puppet-agent[23914]: Puppet::Type::Docker_compose::ProviderRuby: file docker-compose does not exist
puppet-agent[23914]: Could not find a suitable provider for docker_compose
```

After adding to cron:
```
export PATH=$PATH:/usr/local/bin ; puppet agent -t
```
It works.

I resolved it by adding a link:
```
/bin# ln -s /usr/local/bin/
```
It would be nice to have it solved on module level I guess.

### PR DESCRIPTION
**Pull request by AblionGE**
Give the possibility to choose where docker-compose is installed.

### CODE REVIEW

**Comment by AblionGE** [comment]
Any idea on why these tests are failing ? I have the same errors locally with a simple fork of the repo

**Comment by garethr** [comment]
Hi @AblionGE. It looks like this PR needs a quick rebase against master due to some recent changes. Otherwise the change looks good. If you rebase and push I'll take a look if the tests are still failing on Travis.

**Comment by AblionGE** [comment]
I think this time the problem is on your side :)

**Comment by garethr** [comment]
@AblionGE whoops, should be at least running without error now. Rather than merging and leaving the merge commit if you could rebase down to a single commit that cleanly merges into master I'll take another look.

**Comment by AblionGE** [comment]
@garethr done! It seems it works.

**Comment by garethr** [comment]
Thanks @AblionGE

**Pull request merged**
