### PR TITLE
Removed 'restart' init script workaround

### PR DESCRIPTION
**Pull request by solarkennedy**
This code looks like it was a workaround for the misbehaving cid behavior with restart policies.
It is no longer needed. No tests need changing as this code was not under test before.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Er, hold on, need to rebase this off your master.

**Comment by garethr** [comment]
That's not a workaround, but a way of using the built-in docker process manager instead of the init scripts. I'm not 100% on the interface as yet, although it makes sense from a certain point of view it's not very explicit.

Basically, at present, if you set a restart policy for docker, docker will manage the container instead of handing that off to the init system.

**Comment by solarkennedy** [comment]
The restart policy is a good thing, but it doesn't need a special invocation / exec.

It can be in the plain init script. It *already* does this because of the named containers. 
https://github.com/garethr/garethr-docker/blob/master/templates/etc/init.d/docker-run.erb#L91
(stop/start etc)

We (Yelp) were emulating this before with using `extra_params => [ 'restart always']`.
Because even if you use a restart policy, you *still* want an init script, and it is much easier for puppet to control using a `service` than the execs.

**Comment by garethr** [comment]
> you still want an init script

Actually, that's been a previous feature request, where people don't want the init involved and just want to hand this off to Docker. 

This should however be more explicit. It works but it's a little spooky and not well tested as yet.

**Comment by solarkennedy** [comment]
Ok, I'll add some docs instead.

**Pull request closed without merging**
