### PR TITLE
DRY-ing out docker::service

### PR DESCRIPTION
**Pull request by danzilio**

### CODE REVIEW

**Comment by danzilio** [comment]
I feel like a lot of this should be parameterized with most of this logic being moved into `docker::params`

**Comment by garethr** [comment]
@danzilio thanks, and agreed. This looks good. When I have a moment I'll run the acceptance tests and merge. 

Regarding moving things into params, agreed. This is mainly a result of many hands and light work. If you fancy running at that please do.

**Comment by flyinprogrammer** [comment]
THANK YOU FOR THIS WORK!!! you are both amazing!!!

**Comment by danzilio** [comment]
@flyinprogrammer you're very welcome and thank you!

**Pull request merged**
