### PR TITLE
Pull by image digest

### PR DESCRIPTION
**Pull request by RickyCook**
Allows pulling of images by digest so that you can be certain of image content

---

This change is [Reviewable](https://reviewable.io/reviews/garethr/garethr-docker/576)

### CODE REVIEW

**Comment by RickyCook** [comment]
Tests seem to be failing on Ruby 1.9.3 due to `Gem::InstallError: json_pure requires Ruby version ~> 2.0.`. This isn't something I touched, and I think would be failing in master too?

**Comment by DLuCJ** [comment]
wrt json_pure:
https://github.com/puppetlabs/puppet/pull/5152

**Comment by RickyCook** [comment]
Ah right okay. I assume I should ignore that failure then?

**Comment by garethr** [comment]
@RickyCook thanks, much appreciated. I'd spotted the ability to pull via digest but not had time to add it to the module. Good job.

**Comment by andrewsim** [comment]
may I ask when will this be released?

**Pull request merged**
