### PR TITLE
Gh142 support debian

### PR DESCRIPTION
**Pull request by hesco**

### CODE REVIEW

**Comment by arioch** [comment]
What's the current status of this patch?

**Comment by insertjokehere** [comment]
I am also interested in this

**Comment by garethr** [comment]
Master now has Debian support in finally. Thanks for submitting this and apologies for leaving it hanging for ages.

**Comment by hesco** [comment]
good to hear.  Thanks for taking care of that.  Have a machine sitting in the living room waiting for me to upgrade its firmware.  Perhaps when that is done, I can create a new environment, install the latest version of your module and use it to install docker 1.9.  I see that weave has now been integrated with docker.

**Pull request closed without merging**
