### PR TITLE
Updating to avoid key_source and include_src depreciation warnings from puppetlabs-apt

### PR DESCRIPTION
**Pull request by ChrisCrewdson**
I am not sure if this change needs to be locked to a specific puppetlabs-apt version, but it passes all the current tests.

### CODE REVIEW

**Comment by garethr** [comment]
@ChrisCrewdson thanks. This does indeed only work with the 2 series of the apt module.

I'm not going to merge this at this point as doing so forces anyone using this module to update the apt module. I'd rather wait for that to bed down a little and then make the change given it's just implementation. 2.1 of the apt module is backwards compatible so it's not a problem apart from the deprecation warnings.

**Comment by ColinHebert** [comment]
It's been quite a while now. Should this be merged? (2.1 has been released a year ago)

**Comment by erezny** [comment]
This pull request is out of date and no longer works on master. Use https://github.com/garethr/garethr-docker/issues/459 Instead.

**Comment by ChrisCrewdson** [comment]
Closing this very old PR in favor #459.

**Pull request closed without merging**
