### PR TITLE
Networking

### PR DESCRIPTION
**Pull request by scotty-c**
This pull request adds the functionality for the Docker engine 1.9.1 above.

### CODE REVIEW

**Comment by garethr** [comment]
Thanks @scotty-c, I'm finally getting around to going through much of the backlog and I'm particularly interested in getting network support in.

Looking through the PR it needs good rebase with master as the diff is currently showing lots of unrelated changes.

I also didn't spot any tests for the new type and provider?

I'm thinking that I'll use this as a base and put up a separate PR, and I'll work on fleshing out the tests. I'll likely also think about how this integrates with the existing `docker::run` type. Any problems let me know.

**Comment by scotty-c** [comment]
Good morning Gareth,

No worries, if you need me to work on any of it please let me know.

Kind regards
Scott Coulton

On Tuesday, 19 January 2016, Gareth Rushgrove <notifications@github.com>
wrote:

> Thanks @scotty-c <https://github.com/scotty-c>, I'm finally getting
> around to going through much of the backlog and I'm particularly interested
> in getting network support in.
>
> Looking through the PR it needs good rebase with master as the diff is
> currently showing lots of unrelated changes.
>
> I also didn't spot any tests for the new type and provider?
>
> I'm thinking that I'll use this as a base and put up a separate PR, and
> I'll work on fleshing out the tests. I'll likely also think about how this
> integrates with the existing docker::run type. Any problems let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/garethr/garethr-docker/pull/384#issuecomment-172602128>
> .
>


-- 
Kind regards

Scott Coulton

Sent from Gmail Mobile

**Comment by garethr** [comment]
@scotty-c I've put up a new PR adding the `docker_network` type at https://github.com/garethr/garethr-docker/pull/416. If you have time to check it out please let me know what you think.

I've rejigged a few things, mainly around removing the need for the `create => true` param. You should be able to connect containers via the `--net` on run. Thanks for your work on spiking this though, it was useful in getting this in.

**Comment by scotty-c** [comment]
Good evening Gareth,

Yeah it looks really good. I will rebase my other PR and write tests for
the type and provider, then re submit it.

Kind regards

Scott Coulton

On 25 January 2016 at 20:42, Gareth Rushgrove <notifications@github.com>
wrote:

> @scotty-c <https://github.com/scotty-c> I've put up a new PR adding the
> docker_network type at #416
> <https://github.com/garethr/garethr-docker/pull/416>. If you have time to
> check it out please let me know what you think.
>
> I've rejigged a few things, mainly around removing the need for the create
> => true param. You should be able to connect containers via the --net on
> run. Thanks for your work on spiking this though, it was useful in getting
> this in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/garethr/garethr-docker/pull/384#issuecomment-174451921>
> .
>



-- 
Kind regards

Scott Coulton

**Pull request closed without merging**
