### PR TITLE
Added else case for repo_opt

### PR DESCRIPTION
**Pull request by jonnytpuppet**
Added else case for repo_opt

### CODE REVIEW

**Comment by garethr** [comment]
@jonnytpuppet  Does the problem that this is aimed to fix also occur for non-RedHat distros? They won't have `$repo_opt` set?

**Comment by jonnytpuppet** [comment]
Yep I believe so. I added the else clause twice. This PR fixes issues with future parser.

**Comment by jonnytpuppet** [comment]
Actually wait, you're correct, I need to define repo_opt in the other cases. I'll update the PR.

**Comment by garethr** [comment]
@jonnytpuppet thanks. It would be useful to describe the problem, and if possible add a test case, in the title and description of the issue - rather than describing the change. I can more easily review things if I have the context.

**Pull request merged**
