### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by activars**
Correct documentation for run_instance hiera data

### CODE REVIEW

**Comment by garethr** [comment]
I think @ricoli originally added this, as I'm not using this directly at the moment could you confirm if this is correct?

**Comment by ricoli** [comment]
Indeed I did add this section. Didn't add the class include using hiera as not everyone likes to do so, but I guess it doesn't hurt to have it in the readme for clarity sake :)

**Comment by ricoli** [comment]
Oh and I just realised that it should actually be a hash of instances, so the way I wrote it is correct. For clarity, the class should have $instances = {}

**Comment by ricoli** [comment]
Also, the class and readme should also be updated to have $instances = {}, for clarity sake. My bad there!

**Comment by activars** [comment]
The variable is named $instance ...

**Comment by ricoli** [comment]
Indeed @activars, and it was my mistake to do so - should have been instances, as it's a hash :)

**Pull request merged**
