### PR TITLE
Enable setting up the log driver (e.g. `--log-driver syslog`) for Docker daemon

### PR DESCRIPTION
**Pull request by cornelf**
* [x] Ready for review.

### CODE REVIEW

**Comment by tomstockton** [comment]
+1 - I'd like to see this feature merged in.

**Comment by garethr** [comment]
Hi @cornelf. Thanks, this looks like a great addition. Would you be able to add a simple rspec-puppet test as well, that helps with ensuring features don't get broken in the future. The CONTRIBUTING document should help get you started, and the module has lots of example tests, but any questions let me know.

**Comment by arenstar** [comment]
+1

**Comment by rhoml** [comment]
@cornelf @garethr I've made this PR https://github.com/cornelf/garethr-docker/pull/3/files with some tests I would love to see the merged :)

**Comment by rhoml** [comment]
@cornelf @garethr any news? we would love to see this merged soon

**Comment by aleachjr** [comment]
ping @garethr looks like the tests are passing now, how are you feeling about a merge :smile:

**Comment by cornelf** [comment]
:+1:

**Comment by garethr** [comment]
@cornelf thanks alot for this, and sorry for the delay in getting merged. Cheers!

**Comment by rhoml** [comment]
No worries @garethr :D

**Pull request merged**
