### PR TITLE
Future parser fixes

### PR DESCRIPTION
**Pull request by madAndroid**
This change addresses #270 - the issue only occurs when the future parser is enabled: the `dm_*` params that are not explicitly included in the interface for `docker::service` are not in scope, and the storage options are not correctly available to `/etc/sysconfig/docker-storage` (on CentOS7, during my testing)

I have confirmed this by adding the spec tests below prior to the changes to `docker::service`, and running: `PARSER=future bundle exec rake spec` - the spec tests for the storage option changes fail unless the parameters are available in `docker::service`

### CODE REVIEW

**Comment by garethr** [comment]
@madAndroid thanks a lot of tracking this down and putting up the PR. The tests are currently failing under 1.8.7 https://travis-ci.org/garethr/garethr-docker/jobs/91200541. Possibly due to the with_content on the separate line. If you could resolve that I'll merge away.

**Comment by madAndroid** [comment]
@garethr - thanks, sorted :)

**Comment by garethr** [comment]
@madAndroid thanks, much appreciated.

**Comment by madAndroid** [comment]
Awesome, thanks @garethr :)

**Pull request merged**
